modLoader="javafml" #mandatory
loaderVersion="[41,)" 
license="MIT"
[[mods]] 
modId="zelda" 
version="${file.jarVersion}" 
displayName="Breath Of The Wild" 
authors="Majong"
description='''

'''
[[dependencies.zelda]]
    modId="hllib"
    mandatory=true
    versionRange="[194.0.1.0,)"
    ordering="NONE"
    side="BOTH"